# Nixpacks configuration for Railway deployment
providers = ["node"]

[variables]
NODE_VERSION = "18.20.5"
NODE_ENV = "production"

[phases.setup]
cmd = "mkdir -p uploads"

[phases.install]
cmd = "npm ci"

[phases.build] 
cmd = "npm run build"

[start]
cmd = "npm start"
